/** Copy-paste usage shown in Storybook "Show code" for Form. */
export const formUsageCode = [
	'<script>',
	'  import {',
	'    Form,',
	'    FormField,',
	'    PasswordInput,',
	'    Button,',
	'    Checkbox,',
	'    Alert',
	"  } from '@r2digisolutions/components';",
	'',
	'  let errors = $state({});',
	"  let name = $state('');",
	"  let email = $state('');",
	"  let password = $state('');",
	"  let company = $state('');",
	'  let terms = $state(false);',
	'  let loading = $state(false);',
	'  let success = $state(false);',
	'',
	'  function validate() {',
	'    const next = {};',
	"    if (!name.trim()) next.name = 'Name is required';",
	"    if (!email.trim()) next.email = 'Email is required';",
	"    else if (!email.includes('@')) next.email = 'Enter a valid email address';",
	"    if (password.length < 8) next.password = 'Use at least 8 characters';",
	"    if (!terms) next.terms = 'You must accept the terms';",
	'    errors = next;',
	'    return Object.keys(next).length === 0;',
	'  }',
	'',
	'  function clearField(field) {',
	'    if (errors[field]) {',
	'      const next = { ...errors };',
	'      delete next[field];',
	'      errors = next;',
	'    }',
	'  }',
	'',
	'  async function submit() {',
	'    success = false;',
	'    if (!validate()) return;',
	'    loading = true;',
	'    await new Promise((r) => setTimeout(r, 900));',
	'    loading = false;',
	'    success = true;',
	'  }',
	'</script>',
	'',
	'{#if success}',
	'  <Alert variant="success" title="Workspace created" />',
	'{:else}',
	'  <Form',
	'    bind:errors',
	'    {loading}',
	'    title="Account details"',
	'    description="Fields marked with * are required."',
	'    onsubmit={submit}',
	'  >',
	'    <FormField',
	'      label="Full name"',
	'      placeholder="Alex Rivera"',
	'      bind:value={name}',
	'      errorMessage={errors.name}',
	'      required',
	"      oninput={() => clearField('name')}",
	'    />',
	'',
	'    <FormField',
	'      label="Work email"',
	'      type="email"',
	'      placeholder="alex@company.com"',
	'      bind:value={email}',
	'      errorMessage={errors.email}',
	'      required',
	"      oninput={() => clearField('email')}",
	'    />',
	'',
	'    <FormField',
	'      label="Company"',
	'      placeholder="Optional"',
	'      bind:value={company}',
	'      helperText="Shown on invoices and invites."',
	'    />',
	'',
	'    <PasswordInput',
	'      label="Password"',
	'      bind:value={password}',
	'      required',
	"      helperText={errors.password ?? 'At least 8 characters'}",
	"      status={errors.password ? 'error' : 'default'}",
	"      oninput={() => clearField('password')}",
	'    />',
	'',
	'    <Checkbox bind:checked={terms} label="I agree to the Terms and Privacy Policy" />',
	'',
	'    {#snippet footer()}',
	'      <Button type="submit" {loading} fullWidth>Create account</Button>',
	'    {/snippet}',
	'  </Form>',
	'{/if}'
].join('\n');
