/** Copy-paste usage shown in Storybook "Show code" for Form. */
export const formUsageCode = [
	'<script>',
	'  import {',
	'    Form,',
	'    FormField,',
	'    FormPasswordInput,',
	'    FormCheckbox,',
	'    FormSelect,',
	'    FormTextarea,',
	'    FormActions,',
	'    Alert',
	"  } from '@r2digisolutions/components';",
	'',
	'  let data = $state({',
	"    name: '',",
	"    email: '',",
	"    password: '',",
	"    company: '',",
	"    role: '',",
	"    notes: '',",
	'    terms: false',
	'  });',
	'  let errors = $state({});',
	'  let loading = $state(false);',
	'',
	'  function validate() {',
	'    const next = {};',
	"    if (!data.name.trim()) next.name = 'Name is required';",
	"    if (!data.email.trim()) next.email = 'Email is required';",
	"    if (data.password.length < 8) next.password = 'Use at least 8 characters';",
	"    if (!data.role) next.role = 'Select a role';",
	"    if (!data.terms) next.terms = 'You must accept the terms';",
	'    errors = next;',
	'    return Object.keys(next).length === 0;',
	'  }',
	'',
	'  async function submit() {',
	'    if (!validate()) return;',
	'    loading = true;',
	'    await new Promise((r) => setTimeout(r, 900));',
	'    loading = false;',
	'  }',
	'</script>',
	'',
	'<Form bind:data bind:errors {loading} title="Account details" onsubmit={submit}>',
	'  <FormField name="name" label="Full name" bindData required />',
	'  <FormField name="email" label="Work email" type="email" bindData required />',
	'  <FormSelect',
	'    name="role"',
	'    label="Role"',
	"    options={[{ value: 'admin', label: 'Admin' }, { value: 'member', label: 'Member' }]}",
	'    bindData',
	'  />',
	'  <FormPasswordInput name="password" label="Password" bindData required />',
	'  <FormTextarea name="notes" label="Notes" bindData />',
	'  <FormCheckbox name="terms" label="I agree to the Terms" bindData />',
	'',
	'  {#snippet footer()}',
	'    <FormActions submitLabel="Create account" variant="plain" />',
	'  {/snippet}',
	'</Form>'
].join('\n');
